// products.js — Catalogue Pause Attitude.
// Textes marketing repris de pauseattitude.ma/nos-produits ;
// ingrédients / allergènes / valeurs nutritionnelles repris des
// fiches techniques réelles. Prix d'exemple à remplacer.

const PRODUCTS = [
  {
    id: "thon",
    nom_fr: "Le Thon",
    nom_ar: "تونة مايونيز",
    tagline_fr: "Un tour au bord de mer",
    description_fr:
      "Du thon frais et succulent mélangé à une mayonnaise naturelle et légère, agrémenté de salades croquantes. Hissez haut !",
    photo: "https://pauseattitude.ma/wp-content/uploads/2025/06/blanc-captain.jpg",
    video: "",
    couleur: "#3F7EA6",
    halal: false,
    prix_mad: 22,
    poids_gr: 265,
    ingredients_fr:
      "Pain (farine de BLE, eau, levure, sel, GLUTEN), sauce émulsionnée (huile végétale, jaune d'OEUF, eau, vinaigre, sucre, sel, stabilisants E415 ; antioxydant E385), thon 49%, OEUF, herbes et épices, conservateur E202-E211, acidifiants E330, exhausteur de goût E621, épaississant E412-E1442, salade mixte (trévisse, romaine, carottes), tomates.",
    ingredients_ar:
      "خبز (دقيق القمح، ماء، خميرة، ملح، غلوتين)، صلصة مستحلبة (زيت نباتي، صفار البيض، ماء، خل، سكر، ملح)، تونة 49%، بيض، أعشاب وتوابل، سلطة مشكلة، طماطم.",
    allergenes_fr: "produit dans un atelier qui utilise tous les allergènes.",
    allergenes_ar: "منتج مُصنّع في ورشة تُستخدم فيها جميع مسببات الحساسية.",
    energie_kj: 1095,
    energie_kcal: 253,
    lipides_g: 9.7,
    satures_g: 0.8,
    sucres_g: 2.2,
    sel_g: 1.1,
  },
  {
    id: "thon-piquant",
    nom_fr: "Le Thon Piquant",
    nom_ar: "تونة حارة",
    tagline_fr: "Un tour au bord de mer, version relevée",
    description_fr:
      "Du thon frais et succulent mélangé à une mayonnaise naturelle, de la moutarde, le tout agrémenté de tomates et salades croquantes.",
    photo: "https://pauseattitude.ma/wp-content/uploads/2025/06/blanc-captain-1.jpg",
    video: "",
    couleur: "#4A4785",
    halal: false,
    prix_mad: 23,
    poids_gr: 265,
    ingredients_fr:
      "Pain (farine de BLE, eau, levure, sel, GLUTEN), sauce émulsionnée (huile végétale, eau, vinaigre, sucre, légume, pâte de tomate, dextrose, herbes et épices, betterave rouge, stabilisants CMC, gomme xanthane), thon 47%, herbes et épices, conservateur E202-E211, acidifiants E330, exhausteur de goût E621, épaississant E412-E1442, salade mixte (trévisse, romaine, carottes).",
    ingredients_ar:
      "خبز (دقيق القمح، ماء، خميرة، ملح، غلوتين)، صلصة مستحلبة (زيت نباتي، ماء، خل، سكر، خضار، معجون طماطم)، تونة 47%، أعشاب وتوابل، سلطة مشكلة.",
    allergenes_fr: "produit dans un atelier qui utilise tous les allergènes.",
    allergenes_ar: "منتج مُصنّع في ورشة تُستخدم فيها جميع مسببات الحساسية.",
    energie_kj: 839,
    energie_kcal: 200,
    lipides_g: 3.1,
    satures_g: 0.3,
    sucres_g: 2.9,
    sel_g: 1.1,
  },
  {
    id: "club-gouda",
    nom_fr: "Le Club",
    nom_ar: "كلوب جبن غودا",
    tagline_fr: "L'essentiel",
    description_fr:
      "Du beau fromage gouda accompagné de rondelles de tomates et de salade fraîche, un rien de mayonnaise… Un bonheur simple et délicieux !",
    photo: "https://pauseattitude.ma/wp-content/uploads/2025/06/blanc-club.jpg",
    video: "",
    couleur: "#E8B23D",
    halal: false,
    prix_mad: 22,
    poids_gr: 230,
    ingredients_fr:
      "Pain (farine de BLE, eau, levure, sel, GLUTEN), gouda (LAIT pasteurisé, sel, ferments lactiques), mayonnaise (huile de colza, jaune d'ŒUF, vinaigre, sel, sucre, conservateurs E202-E211, stabilisants E412-E415-E142, antioxydant E385, acidifiant E330, MOUTARDE), tomates, salade mixte (trevisse, romaine, carottes).",
    ingredients_ar:
      "خبز (دقيق القمح، ماء، خميرة، ملح، غلوتين)، جبن غودا (حليب مبستر، ملح، خمائر لبنية)، مايونيز (زيت كانولا، صفار البيض، خل، ملح، سكر، خردل)، طماطم، سلطة مشكلة.",
    allergenes_fr: "produit dans un atelier qui utilise tous les allergènes.",
    allergenes_ar: "منتج مُصنّع في ورشة تُستخدم فيها جميع مسببات الحساسية.",
    energie_kj: 1049,
    energie_kcal: 250,
    lipides_g: 8.9,
    satures_g: 4.5,
    sucres_g: 2.2,
    sel_g: 1.1,
  },
  {
    id: "americain",
    nom_fr: "L'Américain",
    nom_ar: "أمريكان لحم بقري خالص",
    tagline_fr: "Le bonheur est dans le pré !",
    description_fr: "Un pur bœuf assaisonné par le chef, sur un lit de salade fraîche.",
    photo: "https://pauseattitude.ma/wp-content/uploads/2025/06/blanc-cowboy.jpg",
    video: "",
    couleur: "#C23B32",
    halal: false,
    prix_mad: 25,
    poids_gr: 265,
    ingredients_fr:
      "Pain (farine de BLE, eau, levure, sel, GLUTEN), américain (viande de bœuf 60%, huile végétale (colza et SOJA), eau, jaune d'ŒUF, vinaigre, sel, amidon de maïs modifié, fines herbes et épices, sauce Worcestershire), sucre, arômes, MOUTARDE, salade mixte (trévisse, romaine, carottes).",
    ingredients_ar:
      "خبز (دقيق القمح، ماء، خميرة، ملح، غلوتين)، أمريكي (لحم بقر 60%، زيت نباتي، ماء، صفار البيض، خل، ملح، نشا ذرة معدل، أعشاب وتوابل)، سكر، منكهات، خردل، سلطة مشكلة.",
    allergenes_fr: "produit dans un atelier qui utilise tous les allergènes.",
    allergenes_ar: "منتج مُصنّع في ورشة تُستخدم فيها جميع مسببات الحساسية.",
    energie_kj: 1227,
    energie_kcal: 293,
    lipides_g: 25.45,
    satures_g: 4.88,
    sucres_g: 2.26,
    sel_g: 1,
  },
  {
    id: "poulet-curry",
    nom_fr: "Le Poulet Curry",
    nom_ar: "دجاج كاري",
    tagline_fr: "Lunch à l'oriental",
    description_fr: "Du poulet assaisonné avec une sauce au curry, agrémenté de salades croquantes.",
    photo: "https://pauseattitude.ma/wp-content/uploads/2025/06/blanc-gandhi.jpg",
    video: "",
    couleur: "#E8C93D",
    halal: true,
    prix_mad: 23,
    poids_gr: 230,
    ingredients_fr:
      "Pain (farine de BLE, eau, levure, sel, GLUTEN), sauce émulsionnée mélangée avec poulet (poulet 50%), huile de colza, eau, jaune d'ŒUF, amidon modifié de maïs, vinaigre, herbes et épices, poudre de curry (MOUTARDE-CELERI), sucre, sel, salade mixte (trévisse, romaine, carottes).",
    ingredients_ar:
      "خبز (دقيق القمح، ماء، خميرة، ملح، غلوتين)، صلصة ممزوجة بالدجاج (دجاج 50%)، زيت كانولا، ماء، صفار البيض، نشا ذرة معدل، خل، أعشاب وتوابل، مسحوق كاري، سكر، ملح، سلطة مشكلة.",
    allergenes_fr: "produit dans un atelier qui utilise tous les allergènes.",
    allergenes_ar: "منتج مُصنّع في ورشة تُستخدم فيها جميع مسببات الحساسية.",
    energie_kj: 1150,
    energie_kcal: 273,
    lipides_g: 9.09,
    satures_g: 1.59,
    sucres_g: 2.45,
    sel_g: 2.06,
  },
  {
    id: "poulet-andalouse",
    nom_fr: "Le Poulet Andalouse",
    nom_ar: "دجاج أندلسي",
    tagline_fr: "Lunch chantant",
    description_fr: "Du poulet assaisonné avec une sauce andalouse, agrémenté de salade mixte.",
    photo: "https://pauseattitude.ma/wp-content/uploads/2025/06/blanc-gandhi.jpg",
    video: "",
    couleur: "#D9603B",
    halal: true,
    prix_mad: 23,
    poids_gr: 260,
    ingredients_fr:
      "Pain (farine de BLE, eau, levure, sel, GLUTEN), sauce émulsionnée mélangée avec viande de poulet (poulet 49%), huile de colza, eau, MOUTARDE, jaune d'ŒUF, sucre, vinaigre, légumes déshydratés, worcestershire (SOJA), herbes et épices, sel, salade mixte (trévisse, romaine, carottes).",
    ingredients_ar:
      "خبز (دقيق القمح، ماء، خميرة، ملح، غلوتين)، صلصة ممزوجة بلحم الدجاج (دجاج 49%)، زيت كانولا، ماء، خردل، صفار البيض، سكر، خل، خضار مجففة، أعشاب وتوابل، ملح، سلطة مشكلة.",
    allergenes_fr: "produit dans un atelier qui utilise tous les allergènes.",
    allergenes_ar: "منتج مُصنّع في ورشة تُستخدم فيها جميع مسببات الحساسية.",
    energie_kj: 1103,
    energie_kcal: 264,
    lipides_g: 11.8,
    satures_g: 1.6,
    sucres_g: 2.3,
    sel_g: 1.1,
  },
  {
    id: "club-dinde",
    nom_fr: "Le Club Filet de Dinde",
    nom_ar: "كلوب فيليه ديك رومي",
    tagline_fr: "L'autre essentiel",
    description_fr:
      "Du filet de dinde, du fromage, accompagnés de rondelles de tomates, le tout agrémenté de salades fraîches et un rien de mayonnaise. Un autre bonheur simple et délicieux.",
    photo: "https://pauseattitude.ma/wp-content/uploads/2025/06/blanc-club-1.jpg",
    video: "",
    couleur: "#A9764F",
    halal: true,
    prix_mad: 24,
    poids_gr: 300,
    ingredients_fr:
      "Pain (farine de BLE, eau, levure, sel, GLUTEN), filet de dinde (86%, eau, huile végétale, sel, sirop de glucose, dextrose, maltodextrine, CELERI), gouda (LAIT pasteurisé, sel, ferments lactiques), mayonnaise (huile de colza, jaune d'ŒUF, vinaigre, sel, sucre, MOUTARDE), tomates, salade mixte (trevisse, romaine, carottes).",
    ingredients_ar:
      "خبز (دقيق القمح، ماء، خميرة، ملح، غلوتين)، فيليه ديك رومي 86%، جبن غودا (حليب مبستر، ملح، خمائر لبنية)، مايونيز (زيت كانولا، صفار البيض، خل، ملح، سكر، خردل)، طماطم، سلطة مشكلة.",
    allergenes_fr: "produit dans un atelier qui utilise tous les allergènes.",
    allergenes_ar: "منتج مُصنّع في ورشة تُستخدم فيها جميع مسببات الحساسية.",
    energie_kj: 1250,
    energie_kcal: 299,
    lipides_g: 13.9,
    satures_g: 3.16,
    sucres_g: 1.35,
    sel_g: 1.1,
  },
];

window.PRODUCTS = PRODUCTS;
